apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-sample-app
spec:
  selector:
    matchLabels:
      appname: node-sample-app
  template:
    metadata:
      labels:
        appname: node-sample-app
    spec:
      tolerations:
          - key: node-role.kubernetes.io/master
      containers:
        - name: node-sample-app
          image: us.icr.io/yash1/node-sample-app:3
          ports:
          - containerPort: 8080
          resources:
              limits:
                memory: 200Mi
              requests:
                memory: 200Mi
